// <auto-generated />
namespace spicy_garden.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class forced1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forced1));
        
        string IMigrationMetadata.Id
        {
            get { return "201509160653553_forced1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
